#!/usr/bin/env ruby

lines = 10
if !ARGV[0].nil? and matches = ARGV[0].match(/\A-(\d+)/)
  lines = matches[1].to_i
  ARGV.shift
end

file = if ARGV[0].nil?
         STDIN
       else
         File.open(ARGV[0])
       end

count = 0
file.each_line do |e|
  break if count >= lines
  puts e
  count += 1
end
